[package]
name = "rpn_calc_no_error_handling"
version = "0.1.0"
authors = ["Asahi Takenouchi <le-soleil-levant.0802@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
